row_garbage_dict = {
    "0": "Power bank",
    "1": "Bags",
    "2": "Toiletries",
    "3": "Plastic toys",
    "4": "Plastic utensils",
    "5": "Plastic hangers",
    "6": "Glassware",
    "7": "Metal utensils",
    "8": "Express paper bags",
    "9": "Plug cords",
    "10": "Old clothes",
    "11": "Cans",
    "12": "Pillows",
    "13": "Plush toys",
    "14": "Shoes",
    "15": "Cutting board",
    "16": "Carton",
    "17": "Condiment bottle",
    "18": "Wine bottle",
    "19": "Metal food can",
    "20": "Metal kitchenware",
    "21": "Pot",
    "22": "Edible oil drum",
    "23": "Beverage bottle",
    "24": "Book paper",
    "25": "Leftovers",
    "26": "Bone",
    "27": "Peel",
    "28": "Tea residue",
    "29": "Vegetables",
    "30": "Eggshells",
    "31": "Fish bones",
    "32": "Battery",
    "33": "Ointments",
    "34": "Expired medicines",
    "35": "Lunch boxes",
    "36": "Dyeing plastic",
    "37": "Cigar",
    "38": "Toothpick",
    "39": "Flowerpot",
    "40": "Ceramics",
    "41": "Chopsticks",
    "42": "Colored paper"
}

garbage_dict = {
    "0": "移动电源",
    "1": "包",
    "2": "盥洗用品",
    "3": "塑料玩具",
    "4": "塑料器皿",
    "5": "塑料衣架",
    "6": "玻璃器皿",
    "7": "金属器皿",
    "8": "快递纸袋",
    "9": "插头线",
    "10": "旧衣服",
    "11": "罐头",
    "12": "枕头",
    "13": "毛绒玩具",
    "14": "鞋子",
    "15": "切菜板",
    "16": "纸箱",
    "17": "调料瓶",
    "18": "酒瓶",
    "19": "金属食品罐",
    "20": "金属厨具",
    "21": "锅",
    "22": "食用油桶",
    "23": "饮料瓶",
    "24": "书纸",
    "25": "剩菜",
    "26": "骨头",
    "27": "果皮",
    "28": "茶渣",
    "29": "蔬菜",
    "30": "蛋壳",
    "31": "鱼骨",
    "32": "电池",
    "33": "药膏",
    "34": "过期药品",
    "35": "午餐盒",
    "36": "染色塑料",
    "37": "雪茄",
    "38": "牙签",
    "39": "花盆",
    "40": "陶瓷器皿",
    "41": "筷子",
    "42": "彩纸"
}

raw_fire_dict = {
    0: "smoke",
    1: "fire"
}

fire_dict = {
    0: "抽烟",
    1: "火"
}


raw_yolov8_dict = {
    0: 'person',
    1: 'bicycle',
    2: 'car',
    3: 'motorcycle',
    4: 'airplane',
    5: 'bus',
    6: 'train',
    7: 'truck',
    8: 'boat',
    9: 'traffic light',
    10: 'fire hydrant',
    11: 'stop sign',
    12: 'parking meter',
    13: 'bench',
    14: 'bird',
    15: 'cat',
    16: 'dog',
    17: 'horse',
    18: 'sheep',
    19: 'cow',
    20: 'elephant',
    21: 'bear',
    22: 'zebra',
    23: 'giraffe',
    24: 'backpack',
    25: 'umbrella',
    26: 'handbag',
    27: 'tie',
    28: 'suitcase',
    29: 'frisbee',
    30: 'skis',
    31: 'snowboard',
    32: 'sports ball',
    33: 'kite',
    34: 'baseball bat',
    35: 'baseball glove',
    36: 'skateboard',
    37: 'surfboard',
    38: 'tennis racket',
    39: 'bottle',
    40: 'wine glass',
    41: 'cup',
    42: 'fork',
    43: 'knife',
    44: 'spoon',
    45: 'bowl',
    46: 'banana',
    47: 'apple',
    48: 'sandwich',
    49: 'orange',
    50: 'broccoli',
    51: 'carrot',
    52: 'hot dog',
    53: 'pizza',
    54: 'donut',
    55: 'cake',
    56: 'chair',
    57: 'couch',
    58: 'potted plant',
    59: 'bed',
    60: 'dining table',
    61: 'toilet',
    62: 'tv',
    63: 'laptop',
    64: 'mouse',
    65: 'remote',
    66: 'keyboard',
    67: 'cell phone',
    68: 'microwave',
    69: 'oven',
    70: 'toaster',
    71: 'sink',
    72: 'refrigerator',
    73: 'book',
    74: 'clock',
    75: 'vase',
    76: 'scissors',
    77: 'teddy bear',
    78: 'hair drier',
    79: 'toothbrush'
}

yolov8_dict = {
    0: '人',
    1: '自行车',
    2: '汽车',
    3: '摩托车',
    4: '飞机',
    5: '公共汽车',
    6: '火车',
    7: '卡车',
    8: '船',
    9: '红绿灯',
    10: '消防栓',
    11: '停车标志',
    12: '停车收费表',
    13: '长椅',
    14: '鸟',
    15: '猫',
    16: '狗',
    17: '马',
    18: '羊',
    19: '牛',
    20: '大象',
    21: '熊',
    22: '斑马',
    23: '长颈鹿',
    24: '背包',
    25: '雨伞',
    26: '手提包',
    27: '领带',
    28: '手提箱',
    29: '飞盘',
    30: '滑雪板',
    31: '滑雪板',
    32: '运动球',
    33: '风筝',
    34: '棒球棒',
    35: '棒球手套',
    36: '滑板',
    37: '冲浪板',
    38: '网球拍',
    39: '瓶子',
    40: '酒杯',
    41: '杯子',
    42: '叉子',
    43: '刀',
    44: '勺子',
    45: '碗',
    46: '香蕉',
    47: '苹果',
    48: '三明治',
    49: '橙子',
    50: '西兰花',
    51: '胡萝卜',
    52: '热狗',
    53: '披萨',
    54: '甜甜圈',
    55: '蛋糕',
    56: '椅子',
    57: '沙发',
    58: '盆栽',
    59: '床',
    60: '餐桌',
    61: '马桶',
    62: '电视',
    63: '笔记本电脑',
    64: '鼠标',
    65: '遥控器',
    66: '键盘',
    67: '手机',
    68: '微波炉',
    69: '烤箱',
    70: '烤面包机',
    71: '水槽',
    72: '冰箱',
    73: '书',
    74: '时钟',
    75: '花瓶',
    76: '剪刀',
    77: '泰迪熊',
    78: '吹风机',
    79: '牙刷'
}

hat_dict = {0: 'hat', 1: 'person'}

vest_dict = {0: 'others', 1: 'work vest'}
