row_garbage_dict = {
    "0": "Power bank",
    "1": "Bags",
    "2": "Toiletries",
    "3": "Plastic toys",
    "4": "Plastic utensils",
    "5": "Plastic hangers",
    "6": "Glassware",
    "7": "Metal utensils",
    "8": "Express paper bags",
    "9": "Plug cords",
    "10": "Old clothes",
    "11": "Cans",
    "12": "Pillows",
    "13": "Plush toys",
    "14": "Shoes",
    "15": "Cutting board",
    "16": "Carton",
    "17": "Condiment bottle",
    "18": "Wine bottle",
    "19": "Metal food can",
    "20": "Metal kitchenware",
    "21": "Pot",
    "22": "Edible oil drum",
    "23": "Beverage bottle",
    "24": "Book paper",
    "25": "Leftovers",
    "26": "Bone",
    "27": "Peel",
    "28": "Tea residue",
    "29": "Vegetables",
    "30": "Eggshells",
    "31": "Fish bones",
    "32": "Battery",
    "33": "Ointments",
    "34": "Expired medicines",
    "35": "Lunch boxes",
    "36": "Dyeing plastic",
    "37": "Cigar",
    "38": "Toothpick",
    "39": "Flowerpot",
    "40": "Ceramics",
    "41": "Chopsticks",
    "42": "Colored paper"
}

garbage_dict = {
    "0": "移动电源",
    "1": "包",
    "2": "盥洗用品",
    "3": "塑料玩具",
    "4": "塑料器皿",
    "5": "塑料衣架",
    "6": "玻璃器皿",
    "7": "金属器皿",
    "8": "快递纸袋",
    "9": "插头线",
    "10": "旧衣服",
    "11": "罐头",
    "12": "枕头",
    "13": "毛绒玩具",
    "14": "鞋子",
    "15": "切菜板",
    "16": "纸箱",
    "17": "调料瓶",
    "18": "酒瓶",
    "19": "金属食品罐",
    "20": "金属厨具",
    "21": "锅",
    "22": "食用油桶",
    "23": "饮料瓶",
    "24": "书纸",
    "25": "剩菜",
    "26": "骨头",
    "27": "果皮",
    "28": "茶渣",
    "29": "蔬菜",
    "30": "蛋壳",
    "31": "鱼骨",
    "32": "电池",
    "33": "药膏",
    "34": "过期药品",
    "35": "午餐盒",
    "36": "染色塑料",
    "37": "雪茄",
    "38": "牙签",
    "39": "花盆",
    "40": "陶瓷器皿",
    "41": "筷子",
    "42": "彩纸"
}

raw_fire_dict = {
    0: "smoke",
    1: "fire"
}

fire_dict = {
    0: "抽烟",
    1: "火"
}
